# Generated by Django 4.2.2 on 2023-07-24 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="creation datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated datetime"),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        help_text="Merchant code identifier",
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(1000)],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Merchant name", max_length=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("nonactive", "Non-active"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        help_text="Merchant status",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "merchant_merchants",
                "ordering": ["-created_at"],
            },
        ),
    ]
