# Generated by Django 4.2.2 on 2023-06-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0004_walletbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=255, unique=True)),
                (
                    "origin_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("to_address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "from_currency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("to_currency", models.CharField(blank=True, max_length=50, null=True)),
                ("network", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=25, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("proof_of_payment", models.TextField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_transactions",
                        to="account.account",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_cancelled_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_transactions",
                        to="account.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "recharge_transactions",
            },
        ),
    ]
