# Generated by Django 4.2.2 on 2023-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recharge", "0002_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="blockchain",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
