# Generated by Django 4.2.2 on 2023-07-25 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recharge", "0002_transaction_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="callback_url",
            field=models.TextField(
                blank=True,
                help_text="Callback url when transactions status change",
                max_length=1000,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
