# Generated by Django 4.2.2 on 2023-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recharge", "0003_transaction_callback_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="origin_code",
            field=models.CharField(
                blank=True,
                help_text="Origin transaction if the transaction is derived from another transaction",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
