# Generated by Django 4.2.2 on 2023-06-30 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0006_alter_account_email_alter_account_user_id_and_more"),
        ("recharge", "0004_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                help_text="Related account object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_transactions",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Separated by a dot, the amount to be received (e.g., 0.001)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="user performing approve action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="blockchain",
            field=models.CharField(
                blank=True,
                help_text="Related blockchain that will be used",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cancel_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason why the transaction becomes canceled",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="user performing cancell action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_cancelled_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="code",
            field=models.CharField(
                help_text="Code of the transaction, also serves as the transaction identifier",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="creation datetime"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="user performing create action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="deleted datetime", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="user performing delete action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_deleted_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="expired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The expiration of the transaction before it gets ignored",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_address",
            field=models.CharField(
                blank=True,
                help_text="Currency address that sends in the transaction",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_currency",
            field=models.CharField(
                blank=True,
                help_text="Symbol of the source currency such as BTC, ETH, etc",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="network",
            field=models.CharField(
                blank=True,
                help_text='Blockchain network \n\nNetwork rule:\nIn a production env network value "mainnet" for all blockchain.\nElse, "ethereum" use "goerli", "ethereum-classic" use "mordor",\n"tron" use "nile", rest use "testnet".\n',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="origin_code",
            field=models.CharField(
                blank=True,
                help_text="Origin transaction if the transaction is derived from another transaction",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="proof_of_payment",
            field=models.TextField(
                blank=True,
                help_text="Image in base64 format of the transaction receipt",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Separated by a dot, exchange rate if different currencies",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_id",
            field=models.CharField(
                blank=True,
                help_text="The transaction hash (txid)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirming", "Confirming"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Transaction status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="Currency address that receives in the transaction",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_currency",
            field=models.CharField(
                blank=True,
                help_text="Symbol of the target currency such as BTC, ETH, etc",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="updated datetime"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                help_text="Related wallet object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet_transactions",
                to="account.wallet",
            ),
        ),
    ]
