# Generated by Django 4.2.2 on 2023-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recharge", "0005_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="The transaction hash (txid)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
