# Generated by Django 4.2.2 on 2023-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recharge",
            "0005_alter_transaction_account_alter_transaction_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                help_text="The transaction type",
                max_length=20,
                null=True,
            ),
        ),
    ]
