# Generated by Django 4.2.2 on 2023-07-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletAttribut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="creation datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated datetime"),
                ),
                (
                    "address_qr",
                    models.TextField(
                        blank=True,
                        help_text="Base64 representation of the wallet address",
                        null=True,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Wallet blockchain symbol (e.g., ETH, BTC, etc.)",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "logo",
                    models.TextField(
                        blank=True,
                        help_text="URL path to the wallet blockchain logo",
                        null=True,
                    ),
                ),
                (
                    "wallet",
                    models.OneToOneField(
                        help_text="Related wallet object",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributs",
                        to="account.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "account_wallet_attributs",
            },
        ),
    ]
