# Generated by Django 4.2.2 on 2023-07-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_walletbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="creation datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="updated datetime"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("success", "Success"),
                            ("fail", "Fail"),
                        ],
                        default="open",
                        help_text="Number of attemp running task",
                        max_length=20,
                    ),
                ),
                (
                    "attemp",
                    models.PositiveIntegerField(default=0, help_text="Status task"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet id related",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_tasks",
                        to="account.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "account_wallet_tasks",
            },
        ),
    ]
