# Generated by Django 4.2.2 on 2023-06-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_walletbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="creation datetime"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                help_text="email of the user register", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("nonactive", "Non-active"),
                    ("suspended", "Suspended"),
                ],
                default="nonactive",
                help_text="status of the account",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="updated datetime"),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_id",
            field=models.PositiveIntegerField(
                help_text="user_id of the user register", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(
                help_text="username of the user register", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                editable=False, help_text="uniq uuid ot user register", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="account",
            field=models.ForeignKey(
                help_text="account object related",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(
                help_text="the string address of the blockchain wallet",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="blockchain",
            field=models.CharField(
                help_text="related blockchain that will be used", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="creation datetime"
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(
                help_text="label of the wallet", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="network",
            field=models.CharField(
                help_text="blokchain network, \nIn Production env use mainnet for all blockchain,\nelse ethereum use goerli, ethereum-classic use mordor,\ntron use nile, rest use testnet.\n",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("nonactive", "Non-active"),
                    ("suspended", "Suspended"),
                ],
                default="nonactive",
                help_text="status of the wallet",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="updated datetime"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user_id",
            field=models.PositiveIntegerField(
                help_text="id of containing user, source account.user_id"
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="address_qr",
            field=models.TextField(
                blank=True, help_text="base64 wallet address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="creation datetime"
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="logo",
            field=models.TextField(
                blank=True, help_text="wallet blochchain logo path url", null=True
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="wallet blockchian symbol ex: ETH, BTC, etc",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="updated datetime"),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="wallet",
            field=models.OneToOneField(
                help_text="wallet object related",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributs",
                to="account.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="nominal amount of wallet",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="creation datetime"
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="created_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="remote wallet create timestamp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="symbol of wallet currency",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="updated datetime"),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="wallet",
            field=models.OneToOneField(
                blank=True,
                help_text="wallet object related",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance",
                to="account.wallet",
            ),
        ),
    ]
