# Generated by Django 4.2.2 on 2023-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_wallettask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettask",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("success", "Success"),
                    ("fail", "Fail"),
                    ("cencel", "Cancel"),
                ],
                default="open",
                help_text="Number of attemp running task",
                max_length=20,
            ),
        ),
    ]
