# Generated by Django 4.2.2 on 2023-06-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_account_created_at_alter_account_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                help_text="Email of the registered user", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_id",
            field=models.PositiveIntegerField(
                help_text="User ID of the registered user", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(
                help_text="Username of the registered user", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                editable=False,
                help_text="Unique UUID of the registered user",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="account",
            field=models.ForeignKey(
                help_text="Related account object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallets",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="address",
            field=models.CharField(
                help_text="String address of the blockchain wallet",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="blockchain",
            field=models.CharField(
                help_text="Related blockchain that will be used", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="label",
            field=models.CharField(
                help_text="Label of the wallet", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="network",
            field=models.CharField(
                help_text='Blockchain network \n\nNetwork rule:\nIn a production env network value "mainnet" for all blockchain.\nElse, "ethereum" use "goerli", "ethereum-classic" use "mordor",\n"tron" use "nile", rest use "testnet".\n',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="user_id",
            field=models.PositiveIntegerField(
                help_text="ID of the associated user (source: account.user_id)"
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="address_qr",
            field=models.TextField(
                blank=True,
                help_text="Base64 representation of the wallet address",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="logo",
            field=models.TextField(
                blank=True,
                help_text="URL path to the wallet blockchain logo",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="symbol",
            field=models.CharField(
                blank=True,
                help_text="Wallet blockchain symbol (e.g., ETH, BTC, etc.)",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletattribut",
            name="wallet",
            field=models.OneToOneField(
                help_text="Related wallet object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributs",
                to="account.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Nominal amount in the wallet",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="created_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of when the remote wallet was created",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="unit",
            field=models.CharField(
                blank=True,
                help_text="Symbol of the wallet currency",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walletbalance",
            name="wallet",
            field=models.OneToOneField(
                blank=True,
                help_text="Related wallet object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance",
                to="account.wallet",
            ),
        ),
    ]
