# Generated by Django 4.2.2 on 2023-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_walletbalance_last_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettask",
            name="transaction_code",
            field=models.CharField(
                blank=True,
                help_text="Transaction code related",
                max_length=255,
                null=True,
            ),
        ),
    ]
