# Generated by Django 4.2.2 on 2023-07-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_wallettask_transaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="network",
            field=models.CharField(
                blank=True,
                help_text="Network of the wallet currency",
                max_length=20,
                null=True,
            ),
        ),
    ]
