# Generated by Django 4.2.2 on 2023-07-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0001_initial"),
        ("account", "0008_wallet_network"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="walletattribut",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="walletbalance",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wallettask",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="account",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="merchant of the system",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="merchant.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the registered user",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user_id",
            field=models.PositiveIntegerField(
                help_text="User ID of the registered user"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Username of the registered user",
                max_length=255,
                null=True,
            ),
        ),
    ]
