# Generated by Django 4.2.2 on 2023-07-25 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("merchant", "0001_initial"),
        ("account", "0009_alter_account_options_alter_wallet_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                help_text="merchant of the system",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant_wallets",
                to="merchant.merchant",
            ),
        ),
    ]
